# Generated by Django 5.1.5 on 2025-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofil', '0002_profile_github_profile_instagram_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-star', help_text='أدخل اسم الكلاس من Font Awesome مثل: fab fa-python', max_length=100),
            preserve_default=False,
        ),
    ]
