# Generated by Django 5.2 on 2025-08-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofil', '0003_skill_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('app', ' Mobile Application'), ('product', 'Product'), ('brand', 'Brand'), ('web', 'Web Aplication')], max_length=50),
        ),
    ]
